---
title: "2020 Week 3 - Passwords"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
library(cowplot)
library(ggwordcloud)
```

Get data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 3)

passwords <- tuesdata$passwords
```

Make plot
```{r}
#Show popluar passwords

plot_data <- passwords %>% 
         head(40) %>% 
         mutate(rank_alt = rev(rank_alt),
                angle = 90 * sample(c(0, 1), n(), replace = TRUE, prob = c(60, 40)),
                colour = sample(c("0","1","2", "3"), n(), replace = TRUE, prob = c(25, 25, 25, 25)))

p <- ggplot(plot_data)+
  geom_text_wordcloud(aes(label = password, size = rank_alt, angle = angle, colour = colour, alpha = rank_alt), eccentricity = 1)+
  scale_radius(range = c(0,30), limits = c(0, NA))+
  scale_colour_manual(values = c("0" = "#2C99B9", "1" = "#29C759", "2" = "#D8780C", "3" = "#893D84"))+
  ggtitle("Popular Passwords")+
  theme_minimal()+
  theme(plot.background = element_rect(fill = "#463F3E"),
        plot.title = element_text(colour = "white", hjust = 0.5, size = 40))
```

Save plot
```{r}
ggdraw(p)
ggsave(here::here("plots", "2020_3", "2020_3_Passwords.png"), 
       width = 15, height = 9, device = "png")
```

