---
title: "2020 Week 12 - The Office"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
library(cowplot)
```

Get data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 12)
office_ratings  <- tuesdata$office_ratings
```

Make plot
```{r}
#Show the ratings of the seasons and individual episodes

get_png <- function(filename) {
  grid::rasterGrob(png::readPNG(here::here("img", filename)), interpolate = TRUE)
}
logo <- get_png("the_office_logo.png")

plot_data <- office_ratings  %>% 
  mutate(x = row_number(),
         season = paste("Season", season)) %>% 
  group_by(season) %>% 
  mutate(avg_rating = mean(imdb_rating),
         placement = min(x))

p <- ggplot(plot_data)+
  # geom_line(aes(x = x, y = total_votes/900+5), colour = "blue", alpha = 0.2)+
  geom_point(aes(x = x, y = imdb_rating, colour = season), size = 1, shape = 1)+
  geom_line(aes(x = x, y = avg_rating, colour = season), size = 1)+
  geom_segment(aes(x = x, xend = x, y = imdb_rating, yend = avg_rating, colour = season))+
  geom_text(aes(x = placement + 7, y = avg_rating + 0.05, label = season, colour = season), size = 6)+
  annotation_custom(logo, xmin = 8, xmax = 90, ymin = 6.5, ymax = 7.3)+
  theme_bw()+
  theme_minimal()+
  theme(panel.border = element_rect(fill = NA, colour = NA),
        panel.background = element_rect(fill = NA, colour = NA),
        plot.background = element_rect(fill = "black", colour = "black"),
        panel.grid.major.y = element_line(colour = "#262626"),
        axis.title.y = element_text(colour = "white", size = 20),
        axis.text.y = element_text(colour = "white", size = 20),
        plot.title = element_text(colour = "white", size = 40, hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = "none",
        panel.grid.minor = element_blank())+
  labs(y = "IMDB Rating")+
  ggtitle("IMDB Ratings for The Office")+
  scale_y_continuous(breaks = seq(from = 6.5, to = 10, by = 0.5), labels = seq(from = 6.5, to = 10, by = 0.5), limits = c(6.5, 10))
```

Save plot
```{r}
ggdraw(p)
ggsave(here::here("plots", "2020_12", "2020_12_TheOffice.png"), 
       width = 15, height = 9, device = "png")
```

